language: python
python:
  - "3.5.3"

install:
  - python3 setup.py install
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install nose
  - pip3 install codeclimate-test-reporter

script: 
  - nosetests --with-coverage
  - codeclimate-test-reporter --file .coverage
